function authHTML(mode='login',message=''){
 const reg=mode==='register';
 return `<div class="auth-page"><div class="auth-logo">P</div><h1>Personal Manager</h1><p class="auth-welcome">${reg?'Create your account':'Welcome back'}</p>${message?`<div class="auth-error">${escapeHTML(message)}</div>`:''}<form id="authForm">${reg?`<div class="field"><label>Name</label><input id="authName" type="text" autocomplete="name" placeholder="Your name" required></div>`:''}<div class="field"><label>Email</label><input id="authEmail" type="email" autocomplete="email" placeholder="you@example.com" required></div><div class="field"><label>Password</label><input id="authPassword" type="password" autocomplete="${reg?'new-password':'current-password'}" placeholder="${reg?'At least 6 characters':'Your password'}" minlength="6" required></div>${reg?`<div class="field"><label>Confirm password</label><input id="authConfirmPassword" type="password" autocomplete="new-password" minlength="6" required></div>`:''}<button class="btn primary full" id="authSubmitBtn" type="submit">${reg?'Create Account':'Login'}</button></form><div class="auth-links">${!reg?`<button class="btn" id="forgotPasswordBtn" type="button">Forgot Password?</button><span>Don't have an account?</span><button class="btn" id="showRegisterBtn" type="button">Create Account</button>`:`<span>Already have an account?</span><button class="btn" id="showLoginBtn" type="button">Back to Login</button>`}</div></div>`;
}
function showAuth(mode='login',message=''){
 document.getElementById('authRoot').innerHTML=authHTML(mode,message);
 const form=document.getElementById('authForm');
 form.onsubmit=async e=>{e.preventDefault();const c=window.supabaseClient;if(!c){showAuth(mode,'Supabase is not configured.');return;}const email=document.getElementById('authEmail').value.trim();const password=document.getElementById('authPassword').value;const btn=document.getElementById('authSubmitBtn');btn.disabled=true;btn.textContent=mode==='register'?'Creating...':'Logging in...';try{if(mode==='register'){const name=document.getElementById('authName').value.trim();const confirm=document.getElementById('authConfirmPassword').value;if(password!==confirm)throw new Error('Passwords do not match.');const {data,error}=await c.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)throw error;if(data.session)window.location.href='index.html';else showAuth('login','Account created. Please check your email to confirm your account, then log in.');}else{const {data,error}=await c.auth.signInWithPassword({email,password});if(error)throw error;window.location.href='index.html';}}catch(err){showAuth(mode,err.message||'Unable to continue.');}};
 if(mode==='login'){
  document.getElementById('forgotPasswordBtn').onclick=async()=>{const c=window.supabaseClient;if(!c){alert('Supabase is not configured.');return;}const email=document.getElementById('authEmail').value.trim();if(!email){alert('Enter your email address first.');return;}try{const redirectTo=new URL('login.html',window.location.href).href;const {error}=await c.auth.resetPasswordForEmail(email,{redirectTo});if(error)throw error;alert('Password reset email sent. Please check your inbox.');}catch(err){alert(err.message||'Unable to send password reset email.');}};
  document.getElementById('showRegisterBtn').onclick=()=>showAuth('register');
 }else document.getElementById('showLoginBtn').onclick=()=>showAuth('login');
}
document.addEventListener('DOMContentLoaded',async()=>{const c=window.supabaseClient;if(!c){showAuth('login','Supabase is not configured.');return;}const {data}=await c.auth.getSession();if(data.session)window.location.href='index.html';else showAuth('login');});
